In [8]:
# last updated : 02-03-2021
# Notes based on Beginner tutorial

In [45]:
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)       # force NumPy to print the entire array

In [3]:
a = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [12]:
type(a)

numpy.ndarray

In [4]:
# the number of axes (dimensions) of the array.
a.ndim

2

In [5]:
# the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
# For a matrix with n rows and m columns, shape will be (n,m). 
a.shape

(3, 3)

In [6]:
# the total number of elements of the array
a.size

9

In [11]:
# the type of the elements in the array.
a.dtype.name

'int64'

In [9]:
# the size in bytes of each element of the array
a.itemsize # (64/8)

8

In [10]:
# the buffer containing the actual elements of the array.
a.data

### *Array Creation*

You can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [13]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
a.dtype.name

'int64'

In [19]:
arr = [[1.2,3.4],[5.6, 7.8]]
a = np.array(arr, dtype=complex)
print(a)

[[1.2+0.j 3.4+0.j]
 [5.6+0.j 7.8+0.j]]


In [20]:
a.shape

(2, 2)

In [21]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


The function **zeros** creates an array full of zeros, the function **ones** creates an array full of ones, and the function **empty** creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.empty((2,2), dtype = np.int32)

array([[ 1262747648, -2117160148],
       [      16280, -1610612736]], dtype=int32)

To create sequences of numbers, NumPy provides the ***arange*** function which is analogous to the Python built-in range, but returns an array.

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(2,10,2) #(start, stop(upto but not include), step)

array([2, 4, 6, 8])

In [33]:
np.arange(0,2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When **arange*** is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function **linspace** that receives as an argument the number of elements that we want, instead of the step

In [35]:
# 10 numbers from 0 to 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### *Printing Arrays*

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [39]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [40]:
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [44]:
a = np.arange(1000).reshape(10,10,10)
print(a)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 225 2

### *Basic Operations*

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method

In [47]:
a = np.arange(4)
b = np.array([10,100,1000,1000])

In [50]:
print(f'a : {a}')
print(f'b : {b}')

a : [0 1 2 3]
b : [  10  100 1000 1000] 


In [51]:
a+b

array([  10,  101, 1002, 1003])

In [52]:
a-b

array([ -10,  -99, -998, -997])

In [54]:
a*b  # elementwise product

array([   0,  100, 2000, 3000])

In [55]:
a@b  # matrix product

5100

In [56]:
a/b

array([0.   , 0.01 , 0.002, 0.003])

In [57]:
b**2

array([    100,   10000, 1000000, 1000000])

In [59]:
10 * np.sin(a)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [61]:
b <= 100

array([ True,  True, False, False])

In [63]:
a += 3
print(a)

[6 7 8 9]


In [64]:
a *= 3
print(a)

[18 21 24 27]


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [67]:
a = np.random.random((2,3))
print(a)

[[0.59927451 0.27878448 0.65630475]
 [0.75615868 0.81274881 0.18347459]]


In [68]:
a.sum()

3.2867458293403846

In [69]:
np.sum(a)

3.2867458293403846

In [71]:
a.min()

0.1834745895823675

In [72]:
np.min(a)

0.1834745895823675

In [73]:
a.max()

0.8127488141039089

In [74]:
np.max(a)

0.8127488141039089

In [77]:
b = np.arange(12).reshape(3,4)
b.cumsum()    # cumilative sum

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [78]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### *Universal Functions*

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [80]:
b = np.arange(8)
print(b)

[0 1 2 3 4 5 6 7]


In [81]:
np.sin(a)

array([[0.56404356, 0.27518727, 0.61019346],
       [0.68613204, 0.72617974, 0.18244694]])

In [82]:
np.sqrt(a)

array([[0.77412823, 0.52800046, 0.81012638],
       [0.86957385, 0.90152583, 0.42833934]])

In [83]:
np.exp(a)

array([[1.82079736, 1.3215225 , 1.92765599],
       [2.13007816, 2.25409557, 1.20138444]])

In [85]:
np.add(b,b)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [93]:
np.average(b)

3.5

In [89]:
b = np.array([True, False, False, True])
b.all()

False

In [90]:
b.any()

True

In [91]:
b = np.arange(8)
np.argmin(b)

0

In [92]:
np.argmax(b)

7

In [94]:
np.argsort(b)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [100]:
b = np.random.randn(2,4)
print(b.shape)

(2, 4)


In [102]:
np.transpose(b).shape

(4, 2)

### *Indexing, Slicing and Iterating*



In [105]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [106]:
a[2:5]

array([ 8, 27, 64])

In [107]:
a[:6]

array([  0,   1,   8,  27,  64, 125])

In [108]:
a[2:]

array([  8,  27,  64, 125, 216, 343, 512, 729])

In [109]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [110]:
a[0:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [111]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [112]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [113]:
b[ : ,1] 

array([ 1, 11, 21, 31, 41])

In [114]:
b[1:3, : ]  

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

* x[1,2,...] is equivalent to x[1,2,:,:,:],
* x[...,3] to x[:,:,:,:,3] and
* x[4,...,5,:] to x[4,:,:,5,:].

In [115]:
c = np.array( [[[  0,  1,  2],              
                 [ 10, 12, 13]],
              [[100,101,102],
                [110,112,113]]])

In [116]:
c.shape

(2, 2, 3)

In [117]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [118]:
c[...,2] 

array([[  2,  13],
       [102, 113]])

In [119]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [157]:
a = np.arange(12).reshape(3,4)
i = np.array([1, 1, 2]) 
a[i]

array([[ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
a>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [159]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

### *Shape Manipulation*

An array has a shape given by the number of elements along each axis

The **reshape** function returns its argument with a modified shape, whereas the **ndarray.resize** method modifies the array itself

In [124]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 9., 0., 8.],
       [8., 9., 8., 0.],
       [7., 8., 3., 8.]])

In [125]:
a.ravel() # returns the array, flattened

array([8., 9., 0., 8., 8., 9., 8., 0., 7., 8., 3., 8.])

In [126]:
a.reshape(6,2)  # returns the array with a modified shape

array([[8., 9.],
       [0., 8.],
       [8., 9.],
       [8., 0.],
       [7., 8.],
       [3., 8.]])

In [127]:
a.T  # returns the array, transposed

array([[8., 8., 7.],
       [9., 9., 8.],
       [0., 8., 3.],
       [8., 0., 8.]])

In [130]:
a

array([[8., 9., 0., 8., 8., 9.],
       [8., 0., 7., 8., 3., 8.]])

In [128]:
a.resize((2,6))

In [129]:
a

array([[8., 9., 0., 8., 8., 9.],
       [8., 0., 7., 8., 3., 8.]])

### *Stacking together different arrays*


In [131]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [132]:
np.hstack((a,b))

array([[8., 1., 9., 1.],
       [3., 7., 0., 0.]])

In [133]:
np.vstack((a,b))

array([[8., 1.],
       [3., 7.],
       [9., 1.],
       [0., 0.]])

In [136]:
np.column_stack((a,b))

array([[8., 1., 9., 1.],
       [3., 7., 0., 0.]])

In [137]:
np.row_stack((a,b))

array([[8., 1.],
       [3., 7.],
       [9., 1.],
       [0., 0.]])

In [139]:
np.concatenate((a,b))

array([[8., 1.],
       [3., 7.],
       [9., 1.],
       [0., 0.]])

### *Splitting one array into several smaller ones*

Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.



In [141]:
a = np.floor(10*np.random.random((2,12)))
a

array([[0., 7., 5., 1., 9., 8., 3., 2., 6., 6., 7., 4.],
       [5., 8., 0., 7., 6., 9., 9., 3., 4., 1., 8., 8.]])

In [142]:
np.hsplit(a,3)

[array([[0., 7., 5., 1.],
        [5., 8., 0., 7.]]),
 array([[9., 8., 3., 2.],
        [6., 9., 9., 3.]]),
 array([[6., 6., 7., 4.],
        [4., 1., 8., 8.]])]

In [144]:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[0., 7., 5.],
        [5., 8., 0.]]),
 array([[1.],
        [7.]]),
 array([[9., 8., 3., 2., 6., 6., 7., 4.],
        [6., 9., 9., 3., 4., 1., 8., 8.]])]

In [143]:
np.array_split(a,4)

[array([[0., 7., 5., 1., 9., 8., 3., 2., 6., 6., 7., 4.]]),
 array([[5., 8., 0., 7., 6., 9., 9., 3., 4., 1., 8., 8.]]),
 array([], shape=(0, 12), dtype=float64),
 array([], shape=(0, 12), dtype=float64)]

### *Copies and Views*
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not.

In [145]:
a = np.arange(5)

In [146]:
a = b

In [147]:
b is a

True

In [148]:
c = a.view() # he view method creates a new array object that looks at the same data.

In [149]:
c is a

False

In [150]:
c.base is a # # c is a view of the data owned by a

True

In [152]:
d = a.copy() # The copy method makes a complete copy of the array and its data.

In [153]:
d is a

False

In [154]:
d.base is a

False

### *Functions and Methods Overview*

**Array Creation** <br>
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

**Conversions** <br>
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

**Manipulations** <br>
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

**Questions** <br>
all, any, nonzero, where

**Ordering** <br>
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

**Operations** <br>
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

**Basic Statistics** <br>
cov, mean, std, var

**Basic Linear Algebra** <br>
cross, dot, outer, linalg.svd, vdot



### *Broadcasting rules*

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match.